// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "./node_modules/.bin/tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations require a direct PostgreSQL session rather than Supabase's
    // transaction pooler. Runtime clients continue to use DATABASE_URL.
    url: env("DIRECT_URL"),
  },
});
